### ISSUE TITLE
Push new version to pub.dartlang.org

### ISSUE THREAD

**Issue by nerddigestive** [rxlabz/speech_recognition#28]
I would like to use recent major feature updates in a larger project, however, the most recent build available from pub.dartlang.org is back from November. This prevents us from being able to use features such as the error handling, which is a big deal! I would greatly appreciate it if you could update the package listing with a recent build. We really appreciate the work that you have done on this library already!

Many thanks,

Ed

**Comment by janstol** [comment]
It's not ideal, but you can use:
```
dependencies:
  speech_recognition:
    git:
      url: https://github.com/rxlabz/speech_recognition.git
      ref: master
```
